logging:
  level:
    com.springboot.project: DEBUG
#      com.springboot.project: DEBUG

server.error.include-message: always


management.endpoints.web.exposure.include: '*'

misurls:
  database: "https://midatabase.com"
